- name: Add reset directory
  ansible.builtin.file:
    path: /hxdepots/reset
    mode: '0755'
    owner: perforce
    group: perforce
    state: directory

- name: Add helix_binaries directory
  ansible.builtin.file:
    path: /hxdepots/helix_binaries
    mode: '0755'
    owner: perforce
    group: perforce
    state: directory

- name: Get Perforce SDP
  ansible.builtin.get_url:
    url: https://swarm.workshop.perforce.com/downloads/guest/perforce_software/helix-installer/main/src/reset_sdp.sh
    dest: /hxdepots/reset

- name: Chmod installer
  ansible.builtin.file:
    path: /hxdepots/reset/reset_sdp.sh
    mode: '0755'
    owner: perforce
    group: perforce

- name: Make installer cfg
  ansible.builtin.shell: /hxdepots/reset/reset_sdp.sh -C > /hxdepots/reset/settings.cfg
  when: sdp_release_branch == true

- name: Run installer cfg
  ansible.builtin.shell: /hxdepots/reset/reset_sdp.sh -c /hxdepots/reset/settings.cfg 2>&1 | tee log.reset_sdp
  become: yes
  become_user: root
  when: sdp_release_branch == true

- name: Run dev installer cfg
  ansible.builtin.shell: /hxdepots/reset/reset_sdp.sh -b dev 2>&1 | tee log.reset_sdp
  become: yes
  become_user: root
  when: sdp_release_branch == false
