- hosts: nfs*
  name: NFS host
  gather_facts: True
  roles:
    - { role: ../../ansible/roles/RedHat, when: ansible_os_family == 'RedHat' }
    - { role: ../../ansible/roles/nfs, when: sdp_role == 'nfs' }

  tasks:
  - name: Dump Facts
    delegate_to: localhost
    run_once: true
    copy:
      content: "{{ hostvars[inventory_hostname] | to_nice_json }}"
      dest: dump_facts.json
