- hosts: nfs.*
  name: NFS host
  tasks:

  - name: Upgrade all packages
    ansible.builtin.yum:
      name: '*'
      state: latest
    when: ansible_facts['os_family'] == "RedHat"

  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest
    when: ansible_facts['os_family'] == "Debian"

  - name: Ensure group "perforce" exists with correct gid
    ansible.builtin.group:
      name: perforce
      state: present
      gid: 9004

  - name: Add the user "perforce"
    ansible.builtin.user:
      name: perforce
      comment: Perforce
      shell: /bin/bash
      uid: 9004
      group: perforce
      generate_ssh_key: yes
      ssh_key_bits: 4096
      ssh_key_file: .ssh/perforce.key

  - name: Set authorized key for user "perforce" copying it from current user
    ansible.posix.authorized_key:
      user: perforce
      state: present
      key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/perforce.pub') }}"

  - name: Add file /etc/sudoers.d/perforce
    ansible.builtin.file:
      path: /etc/sudoers.d/perforce
      state: touch
      owner: root
      group: root
      mode: '0600'

  - name: Add sudo for user "perforce"
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/perforce
      state: present
      owner: root
      group: root
      mode: '0400'
      line: 'perforce ALL=(ALL) NOPASSWD:ALL'
      validate: /usr/sbin/visudo -cf %s

  - name: Install NFS-utils rpm
    ansible.builtin.yum:
      name: nfs-utils
      state: present
    when: ansible_facts['os_family'] == "RedHat"

  - name: Install NFS-utils deb
    ansible.builtin.apt:
      name: nfs-common
      state: present
    when: ansible_facts['os_family'] == "Debian"

  - name: Install NFS Server deb
    ansible.builtin.apt:
      name: nfs-kernel-server
      state: present
    when: ansible_facts['os_family'] == "Debian"

  - name: Add hxdepots path
    ansible.builtin.file:
      path: /nfs/hxdepots
      state: directory
      recurse: yes
      owner: nobody
      group: nobody
    when: ansible_facts['os_family'] == "RedHat"

  - name: Add hxdepots path
    ansible.builtin.file:
      path: /nfs/hxdepots
      state: directory
      recurse: yes
      owner: nobody
      group: nogroup
    when: ansible_facts['os_family'] == "Debian"

  - name: Add NFS Export for "commit" and commit-standby
    ansible.builtin.lineinfile:
      path: /etc/exports
      state: present
      owner: root
      group: root
      mode: '0544'
      line: "/nfs/hxdepots {{ network_cidr }}(rw,sync,no_subtree_check)"

  - name: Enable service rpcbind and start
    ansible.builtin.service:
      name: rpcbind
      enabled: yes
      state: started

  - name: Enable service nfs-server and start
    ansible.builtin.service:
      name: nfs-server
      enabled: yes
      state: started
    when: ansible_facts['os_family'] == "RedHat"

  - name: Enable service nfs-kernel-server and start
    ansible.builtin.service:
      name: nfs-kernel-server
      enabled: yes
      state: started
    when: ansible_facts['os_family'] == "Debian"

  - name: Add "Domain" to idmapd.conf
    ansible.builtin.lineinfile:
      path: /etc/idmapd.conf
      state: present
      regexp: '^#Domain.*'
      owner: root
      group: root
      mode: '0544'
      line: Domain = {{ inventory_hostname.split('.', 1)[1] }}
