- name: Get Perforce SDP
  ansible.builtin.get_url:
    url: https://swarm.workshop.perforce.com/downloads/guest/perforce_software/sdp/downloads/sdp.{{sdp_platform}}.{{sdp_release_version}}.{{sdp_archive}}
    dest: /hxdepots/sdp.{{sdp_platform}}.{{sdp_release_version}}.{{sdp_archive}}
  become: true
  become_user: perforce

- name: Unarchive Perforce SDP
  ansible.builtin.unarchive:
    src: /hxdepots/sdp.{{sdp_platform}}.{{sdp_release_version}}.{{sdp_archive}}
    dest: /hxdepots
    remote_src: yes
  become: true
  become_user: perforce

- name: Rrestorecon p4d_1_init
  ansible.builtin.shell: "restorecon -vF /p4/1/bin/p4d_1_init"

- name: Rrestorecon p4d_1_init
  ansible.builtin.shell: "restorecon -vF /p4/1/bin/p4d_1_init"

- name: Rrestorecon p4broker_1_init
  ansible.builtin.shell: "restorecon -vF /p4/1/bin/p4broker_1_init"

- name: Semanage fcontext p4broker_1_init
  ansible.builtin.shell: "semanage fcontext -a -t bin_t /p4/1/bin/p4broker_1_init"


