- name: Commit playbook
  hosts: commit*
  roles:
    - { role: ../../ansible/roles/Debian, when: ansible_os_family == 'Debian' }
    - { role: ../../ansible/roles/RedHat, when: ansible_os_family == 'RedHat' }
    - { role: ../../ansible/roles/Perforce, when: sdp_role == 'commit' }
    - { role: ../../ansible/roles/SDP, when: sdp_role == 'commit' }
  tasks:
  - name: Dump Facts
    delegate_to: localhost
    run_once: true
    copy:
      content: "{{ hostvars[inventory_hostname] | to_nice_json }}"
      dest: dump_facts.json

  - name: Check DNS
    ansible.builtin.shell: "nslookup {{ inventory_hostname }} {{ ansible_default_ipv4.gateway }} |grep Address |grep -v \\# |awk '{print $2}'"
    register: dns_check

  - name: Reboot machine and send a message if DNS is not registered
    ansible.builtin.reboot:
      msg: "Rebooting machine in 5 seconds"
    when:  ansible_default_ipv4.address != dns_check.stdout
