  - name: Add hxlogs path
    ansible.builtin.file:
      path: /hxlogs
      state: directory
      owner: perforce
      group: perforce
      mode: '0755'

  - name: Add hxdepots path
    ansible.builtin.file:
      path: /hxdepots
      state: directory
      owner: perforce
      group: perforce
      mode: '0755'

  - name: Add hxmetadata path
    ansible.builtin.file:
      path: /hxmetadata
      state: directory
      owner: perforce
      group: perforce
      mode: '0755'
