- name: Add hxlogs directory
  ansible.builtin.file:
    path: /hxlogs
    state: directory
    owner: perforce
    group: perforce
    mode: '0755'

- name: Add hxdepots directory
  ansible.builtin.file:
    path: /hxdepots
    state: directory
    owner: perforce
    group: perforce
    mode: '0755'

- name: Add hxmetadata directory
  ansible.builtin.file:
    path: /hxmetadata
    state: directory
    owner: perforce
    group: perforce
    mode: '0755'

- name: Get NFS host IP Address
  ansible.builtin.shell: "nslookup {{ sdp_commit_nfs_host }} |grep Address |grep -v \\# |awk '{print $2}'"
  register: nfs_host_ip

- name: Add NFS mounts
  ansible.builtin.lineinfile:
    path: /etc/fstab
    line: "{{ nfs_host_ip.stdout }}:/nfs/hxdepots /hxdepots nfs defaults 0 0"
    insertafter: '^#'
    owner: root
    group: root
    mode: '0644'

- name: Mount NFS
  ansible.posix.mount:
    path: /hxdepots
    src: "{{ nfs_host_ip.stdout }}:/nfs/hxdepots"
    fstype: nfs
    state: mounted

- name: Create ansible temporary directory
  ansible.builtin.tempfile:
    state: directory
    path: ~/.ansible/tmp
  become: true
  become_user: perforce

- name: Add helix_binaries directory
  ansible.builtin.file:
    path: /hxdepots/helix_binaries/
    state: directory
    owner: perforce
    group: perforce
    mode: '0755'

- name: Get Perforce cli p4
  ansible.builtin.get_url:
    url: https://ftp.perforce.com/perforce/{{ perforce_release }}/bin.{{ perforce_arch }}/p4
    dest: /hxdepots/helix_binaries/
    mode: '0755'
    owner: perforce
    group: perforce

- name: Get Perforce server p4d
  ansible.builtin.get_url:
    url: https://ftp.perforce.com/perforce/{{ perforce_release }}/bin.{{ perforce_arch }}/p4d
    dest: /hxdepots/helix_binaries/
    mode: '0755'
    owner: perforce
    group: perforce

- name: Get Perforce proxy p4p
  ansible.builtin.get_url:
    url: https://ftp.perforce.com/perforce/{{ perforce_release }}/bin.{{ perforce_arch }}/p4p
    dest: /hxdepots/helix_binaries/
    mode: '0755'
    owner: perforce
    group: perforce

- name: Get Perforce proxy p4broker
  ansible.builtin.get_url:
    url: https://ftp.perforce.com/perforce/{{ perforce_release }}/bin.{{ perforce_arch }}/p4broker
    dest: /hxdepots/helix_binaries/
    mode: '0755'
    owner: perforce
    group: perforce
